spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

feign:
  client:
    config:
      user-service:
        url: http://user-service

jwt:
  secret: MySecretKeyForJwtTokenForRBACAuthorization12345!
  expiration: 86400000